// Longer YouTube narration (2-3 min) per lesson. No em dashes. UK English.
// why: one sentence per "why" card. steps: two sentences per step. offer lines follow lesson.offer.
module.exports = {
1: {
  intro: ['Welcome to LinkedIn from Zero, a fourteen day series from Ascendra.', 'Most people join LinkedIn, add a job title, and then forget about it.', 'In this first lesson, you will see why LinkedIn might be the most important page about you online.'],
  why: ['First, recruiters search it. Many hiring teams look you up on LinkedIn before they ever call you.', 'Second, it holds your network. Former colleagues, clients and friends are all in one place.', 'And third, it is always on. Your profile keeps working for you, even while you sleep.'],
  steps: [
    ['Step one, understand what LinkedIn is.', 'Think of it as an online CV, plus real conversations with people in your industry.'],
    ['Step two, see who is there.', 'Recruiters, managers, founders and future clients are already using it every day.'],
    ['Step three, set your goal.', 'Are you looking for a new job, new clients, or simply to learn? Your goal shapes everything else.'],
    ['Step four, give it fifteen minutes a day.', 'Small daily habits beat big bursts, and consistency is what builds visibility.'],
    ['Step five, follow this series.', 'One lesson a day for fourteen days, from zero to a profile that really works.']],
  doAvoid: 'Treat your profile like a living CV, and start before you need it. Avoid waiting until you are job hunting, and do not copy someone else\'s profile.',
  tip: 'Before tomorrow, write down your one main LinkedIn goal.',
  outro: ['That is lesson one.', 'Subscribe to Ascendra, and I will see you tomorrow for lesson two, setting up your account the right way.'],
},
2: {
  intro: ['Welcome back to LinkedIn from Zero. This is lesson two.', 'Before you write a single word on your profile, there are five settings to get right.', 'They take ten minutes, and they save you a lot of trouble later.'],
  why: ['A clean setup makes you look professional from day one.', 'A tidy profile link is easy to share on your CV and in your email signature.', 'And the right privacy settings decide who can actually find you.'],
  steps: [
    ['Step one, sign up with your personal email.', 'Do not use your work email, because you could lose access if you change jobs.'],
    ['Step two, use your real name.', 'Use the same name as on your CV, with no titles or emojis in the name field.'],
    ['Step three, claim your custom URL.', 'Go to public profile settings, and change it to linkedin dot com slash in slash your name.'],
    ['Step four, set your location.', 'Choose where you want to work, because recruiters filter by location.'],
    ['Step five, check your privacy settings.', 'Make sure your profile is visible, so the right people can find you.']],
  doAvoid: 'Add a backup email and phone number, and put your new link on your CV. Avoid random numbers in your URL, and never leave your profile private.',
  tip: 'Turn on two step verification, in settings, under sign in and security.',
  outro: ['That is lesson two.', 'Subscribe to Ascendra, and tomorrow we will make your photo and banner build trust.'],
},
3: {
  intro: ['This is lesson three of LinkedIn from Zero.', 'People decide in seconds whether to read your profile.', 'And that decision is made by two images: your photo and your banner.'],
  why: ['Your photo is seen first, before anyone reads a single word.', 'A friendly face builds trust and makes you look approachable.', 'And your banner is free advertising, it can say exactly what you do.'],
  steps: [
    ['Step one, use a recent photo.', 'It should look like you today, head and shoulders, with your face clearly visible.'],
    ['Step two, find good light and a plain background.', 'Face a window for soft daylight, and avoid busy or dark backgrounds.'],
    ['Step three, look approachable.', 'A natural smile works well, and dress the way you would for work.'],
    ['Step four, design a simple banner.', 'Free tools like Canva work well. The recommended size is fifteen eighty four by three ninety six pixels.'],
    ['Step five, put one message on it.', 'Say what you do and who you help, and keep the text short and easy to read.']],
  doAvoid: 'Use a high quality photo, and check how both images look on your phone. Avoid group photos, sunglasses, logos instead of your face, and the default blue banner.',
  tip: 'Ask a friend to take your photo near a window in daylight.',
  outro: ['That is lesson three.', 'Subscribe to Ascendra, and tomorrow I will share a simple formula for a headline that gets clicks.'],
},
4: {
  intro: ['Welcome to lesson four of LinkedIn from Zero.', 'Your headline is the line under your name.', 'It follows you everywhere on LinkedIn, so it is worth getting right.'],
  why: ['It appears next to your name in search results.', 'It shows on every post and every comment you make.', 'And it tells people what you do at a glance.'],
  steps: [
    ['Step one, start with your role.', 'Use the job title you want, in the words people actually search for.'],
    ['Step two, say who you help.', 'Name your audience or industry, for example small businesses or school leavers.'],
    ['Step three, add the result.', 'What changes because of you? Keep it specific and simple.'],
    ['Step four, include two or three keywords.', 'Use the skills recruiters search for, and separate them with a straight line symbol.'],
    ['Step five, read it out loud.', 'It should sound clear and human, with no jargon. You have up to two hundred and twenty characters.']],
  doAvoid: 'Write for the reader, and update your headline as you grow. Avoid words like guru or ninja, and never just write unemployed or student.',
  tip: 'The formula is: role, who you help, and the result you deliver.',
  outro: ['That is lesson four.', 'Subscribe to Ascendra, and tomorrow we will write an About section that people actually read.'],
},
5: {
  intro: ['This is lesson five of LinkedIn from Zero.', 'Your About section is the only place on LinkedIn where you tell your story in your own words.', 'Here is a simple structure you can use today.'],
  why: ['It is your story, told in your own voice.', 'It builds connection, because people hire people they understand.', 'And it adds more keywords, which helps you appear in more searches.'],
  steps: [
    ['Step one, open with a strong hook.', 'Only the first few lines show before see more, so make them bold and clear.'],
    ['Step two, say who you are.', 'Describe your role and experience in plain, friendly language.'],
    ['Step three, add proof.', 'Share two or three results or achievements. Numbers help when you have them.'],
    ['Step four, list your key skills.', 'Keep it short, and use the same words you see in job adverts.'],
    ['Step five, finish with a call to action.', 'Tell people how to reach you, by email or by sending you a message.']],
  doAvoid: 'Write in the first person, and keep your paragraphs short. Avoid copying your CV word for word, and avoid one long block of text.',
  tip: 'Write it in a notes app first, then paste it into LinkedIn.',
  outro: ['That is lesson five.', 'Subscribe to Ascendra, and tomorrow we will turn your experience into real results.'],
},
6: {
  intro: ['Welcome to lesson six of LinkedIn from Zero.', 'Recruiters do not want to read your job description.', 'They want to know what changed because of you.'],
  why: ['Results prove your value to your next employer.', 'Job titles and skills in this section help you get found.', 'And matching your CV builds trust with recruiters.'],
  steps: [
    ['Step one, add every relevant role.', 'Use the correct titles and dates, and link each role to the company page.'],
    ['Step two, write a one line summary.', 'Say what the role was about, and who you supported.'],
    ['Step three, focus on results, not duties.', 'Instead of responsible for tickets, write reduced the ticket backlog by twenty percent.'],
    ['Step four, add skills to each role.', 'Pick them from the LinkedIn skills list, so your skills link to real work.'],
    ['Step five, add media.', 'Attach projects, certificates or links. Show it, do not just tell it.']],
  doAvoid: 'Start each point with an action verb, and use numbers where you can. Avoid copying job descriptions, and make sure your dates match your CV.',
  tip: 'The formula is: action verb, what you did, and the result.',
  outro: ['That is lesson six.', 'Subscribe to Ascendra, and tomorrow we will add the skills that help you get found.'],
},
7: {
  intro: ['This is lesson seven of LinkedIn from Zero.', 'Recruiters filter LinkedIn by skills.', 'If the right skills are missing from your profile, you simply do not show up.'],
  why: ['Recruiters search and filter by skills.', 'LinkedIn matches your skills to job adverts.', 'And endorsements and courses make your skills credible.'],
  steps: [
    ['Step one, list your real skills.', 'Include technical skills and people skills, but only ones you can prove.'],
    ['Step two, check job adverts.', 'Open the jobs you want, and copy the exact skill words they use.'],
    ['Step three, order your top skills.', 'Put the most important ones first, and mention them in your About section.'],
    ['Step four, link skills to your roles.', 'Connect each skill to the job where you used it.'],
    ['Step five, prove them.', 'Add courses and certificates, and ask colleagues to endorse you.']],
  doAvoid: 'Focus on skills for your target job, and keep the list up to date. Never add skills you do not have.',
  tip: 'Compare three job adverts you like, and add the skills that repeat.',
  outro: ['That is lesson seven.', 'Subscribe to Ascendra, and tomorrow we will add proof with Featured and recommendations.'],
},
8: {
  intro: ['Welcome to lesson eight of LinkedIn from Zero.', 'Telling people you are good at your job is fine.', 'Showing it, and having other people say it, is much stronger.'],
  why: ['The Featured section shows your best work near the top of your profile.', 'Recommendations are social proof, others praising you beats praising yourself.', 'And they build trust, because they are hard to fake.'],
  steps: [
    ['Step one, open the Featured section.', 'Click add profile section, then Featured, and pin a few items.'],
    ['Step two, pin your best work.', 'A post, a project, a PDF or a link. Your portfolio works well too.'],
    ['Step three, choose who to ask.', 'Managers, colleagues and clients who know your work well.'],
    ['Step four, ask personally.', 'Send a short, friendly message, and suggest what they could mention.'],
    ['Step five, give first.', 'Write recommendations for other people. Many will return the favour.']],
  doAvoid: 'Update Featured every few months, and thank people who recommend you. Avoid generic requests, and avoid only asking friends.',
  tip: 'This week, give two recommendations before you ask for any.',
  outro: ['That is lesson eight.', 'If you would like a second pair of eyes on your profile, send me a message.', 'Subscribe to Ascendra, and tomorrow we will build a network that opens doors.'],
},
9: {
  intro: ['This is lesson nine of LinkedIn from Zero.', 'Your network decides who sees your profile and your posts.', 'So build it on purpose, not at random.'],
  why: ['Your posts are shown to your network first, so it decides your reach.', 'Many opportunities come through people you know.', 'And your feed is shaped by who you follow, so it is how you learn.'],
  steps: [
    ['Step one, start with people you know.', 'Colleagues, classmates and friends. You can import your contacts if you like.'],
    ['Step two, add your target field.', 'Connect with people in the roles you want, and recruiters in your industry.'],
    ['Step three, add a personal note.', 'Say why you want to connect, in one or two friendly lines.'],
    ['Step four, follow industry voices.', 'Follow leaders and companies you admire, and learn from what they share.'],
    ['Step five, keep it steady.', 'Five to ten new connections a day is plenty. Quality beats quantity.']],
  doAvoid: 'Personalise your requests, thank people who accept, and engage with their posts. Never pitch someone straight after they connect.',
  tip: 'Try: hi Sara, I enjoyed your post on IT support, I would love to connect.',
  outro: ['That is lesson nine.', 'Need help with your profile? Send me a message.', 'Subscribe to Ascendra, and tomorrow we will write your first LinkedIn post.'],
},
10: {
  intro: ['Welcome to lesson ten of LinkedIn from Zero.', 'Writing your first post can feel scary.', 'This simple five part structure makes it easy.'],
  why: ['Posting puts you in front of your whole network.', 'Sharing what you know builds your credibility.', 'And good posts start useful conversations.'],
  steps: [
    ['Step one, the hook.', 'Write a short, bold first line that makes people want to read more.'],
    ['Step two, one story or lesson.', 'Keep to one idea per post, something you learned or did.'],
    ['Step three, make it easy to scan.', 'Use short lines, white space, and simple lists.'],
    ['Step four, ask a question.', 'Invite people to comment, and reply to every comment you get.'],
    ['Step five, add three to five hashtags.', 'Make them relevant to your topic, and put them at the end.']],
  doAvoid: 'Post two or three times a week, and add an image or a document. Avoid waiting for the perfect post, walls of text, and links in the main post.',
  tip: 'An easy first post: three things I learned in my first year as, and then your job.',
  outro: ['That is lesson ten.', 'Write yours this week, and send it to me if you would like feedback.', 'Subscribe to Ascendra, and tomorrow we will grow your reach through comments.'],
},
11: {
  intro: ['This is lesson eleven of LinkedIn from Zero.', 'You do not need to post every day to grow on LinkedIn.', 'Thoughtful comments put you in front of new people every single day.'],
  why: ['Your comments appear to the poster\'s whole audience.', 'People remember those who add value, so it builds relationships.', 'And it is low effort, fifteen minutes a day is enough.'],
  steps: [
    ['Step one, find five to ten voices.', 'Choose people in your target industry, and turn on their notifications.'],
    ['Step two, comment early.', 'Comments in the first hour after a post get seen the most.'],
    ['Step three, add something useful.', 'Share a tip, an example or a question. More than just great post.'],
    ['Step four, keep the conversation going.', 'Reply to replies, and turn good conversations into connections.'],
    ['Step five, make it a habit.', 'Fifteen minutes every day, at the same time.']],
  doAvoid: 'Write two or three thoughtful lines, and stay kind even when you disagree. Avoid self promotion in comments, and avoid arguing with strangers.',
  tip: 'Comment before you post. It warms up your audience.',
  outro: ['That is lesson eleven.', 'Need help with LinkedIn? Send me a message.', 'Subscribe to Ascendra, and tomorrow we will use LinkedIn\'s job search tools.'],
},
12: {
  intro: ['Welcome to lesson twelve of LinkedIn from Zero.', 'LinkedIn is not just a profile.', 'It is one of the best job search tools you have, if you use its features.'],
  why: ['Job alerts tell you about new roles quickly, so you can apply first.', 'Open to Work lets recruiters see that you are looking.', 'And filters cut out the roles that do not fit.'],
  steps: [
    ['Step one, turn on Open to Work.', 'Choose your roles and locations, and decide whether only recruiters or everyone can see it.'],
    ['Step two, use the search filters.', 'Filter by location, date posted and experience level, and by remote, hybrid or on site.'],
    ['Step three, set job alerts.', 'Save searches for your target roles, and get notified every day.'],
    ['Step four, follow your target companies.', 'You will see their news and job openings, and you can engage with their posts.'],
    ['Step five, message the hiring team.', 'After you apply, send a short note with one reason you are a good fit.']],
  doAvoid: 'Apply within a few days of a job being posted, and tailor your CV for each role. Avoid relying only on Easy Apply, and avoid applying to everything.',
  tip: 'Follow up politely about a week after you apply.',
  outro: ['That is lesson twelve.', 'If you would like help with your CV or your LinkedIn profile, I offer one to one sessions for twenty pounds an hour.', 'Send me a message, or email hello at ascendra academy dot co dot uk.'],
},
13: {
  intro: ['This is lesson thirteen of LinkedIn from Zero.', 'Recruiters often read your CV, then check your LinkedIn.', 'If the two do not match, it raises questions.'],
  why: ['Matching details build trust with recruiters.', 'Different dates or job titles look like red flags.', 'And using the same keywords helps both pass the filters.'],
  steps: [
    ['Step one, use the same titles and dates.', 'Check every role matches, and explain any gaps the same way.'],
    ['Step two, use the same keywords.', 'Take the words from your target jobs, and use them in both.'],
    ['Step three, keep the CV short and the profile fuller.', 'Your CV should be up to two pages and tailored. Your profile can add context and media.'],
    ['Step four, link them together.', 'Put your LinkedIn link on your CV, and add your CV to Featured if you like.'],
    ['Step five, update both together.', 'New role or new skill? Update both, and review them every few months.']],
  doAvoid: 'Tailor your CV for each job, and ask someone you trust to check both. Avoid conflicting dates, a CV longer than two pages, and an outdated profile.',
  tip: 'Set a reminder to review your CV and LinkedIn every three months.',
  outro: ['That is lesson thirteen.', 'Would you like me to review your CV and LinkedIn together? One to one sessions are twenty pounds an hour.', 'Send me a message to book, and join me tomorrow for the final lesson.'],
},
14: {
  intro: ['Welcome to the final lesson of LinkedIn from Zero.', 'Two weeks ago we started from nothing.', 'Here is your complete checklist, so you can make sure nothing is missing.'],
  why: ['Your profile is ready: photo, headline, About, experience and skills.', 'Your network is growing, with purposeful connections and daily comments.', 'And you are visible, posting, engaging and using the job tools.'],
  steps: [
    ['Area one, setup and settings.', 'Your custom link, location and privacy, with two step verification switched on.'],
    ['Area two, photo, banner and headline.', 'A clear photo, a simple banner, and the headline formula: role, who you help, and the result.'],
    ['Area three, About, experience and skills.', 'A story with proof, experience written as results, and skills that match your target jobs.'],
    ['Area four, proof and network.', 'Featured, recommendations, and connecting with purpose every day.'],
    ['Area five, your habits.', 'Two or three posts a week, daily comments, and job alerts switched on.']],
  doAvoid: 'Save this checklist, and review your profile once a month. Do not stop after two weeks, and do not try to do it all alone.',
  tip: 'Pick the one area that is weakest on your profile, and fix it this week.',
  outro: ['Thank you for following LinkedIn from Zero.', 'If you would like to do it together, I offer one to one LinkedIn and CV help for twenty pounds an hour.', 'Send me a message, or email hello at ascendra academy dot co dot uk. And subscribe to Ascendra for more.'],
},
};
